### ISSUE TITLE
West.yml seems redundant

### ISSUE THREAD

**Issue by tgibson-work** [NXPmicro/mcux-sdk-middleware-multicore#3]
The contents of https://github.com/nxp-mcuxpresso/mcux-sdk-middleware-multicore/blob/main/west.yml duplicates metadata that is in https://github.com/nxp-mcuxpresso/mcux-sdk/blob/main/west.yml, and is in fact conflicting with the information in the other file. Either the west.yml file in this repository is redundant and should be removed, or the metadata should be consistent for a given version (e.g. for the MCUX_2.14.0 tag the west.yml file in this repository uses the url https://github.com/NXPmicro/rpmsg-lite.git and version 5.0.0 for the rpmsg-lite repository, but the west.yml in the mcux-sdk repository uses the url  https://github.com/nxp-mcuxpresso/rpmsg-lite and a different version - 5.1.0).

**Comment by MichalPrincNXP** [comment]
Hi @mcuxsusan , could you please help to address that issue? I think the west.yml is really not needed in this mcux-sdk-middleware-multicore  repo.

**Comment by suchun230** [comment]
Hi @MichalPrincNXP, should erpc and rpmsg-lite be submodule of multicore?

**Comment by mcuxsusan** [comment]
Hi @MichalPrincNXP, does multicore always need eprc and rpmsg-lite? Should erpc and rpmsg-lite be worked as submodule of multicore? I am thinking the case that user maybe customized his own west.yml and have mcux-sdk and multicore added only.

**Comment by MichalPrincNXP** [comment]
Hi @mcuxsusan , yes, the multicore solution as a whole needs both the rpmsg-lite and the erpc repos referenced in the west.yml.
I would rather avoid mixing git submodules and west. Having the west.yml in this mcux-sdk-middleware-multicore repo at least shows the necessary dependency, so I will align the content with the mcux-sdk west.yml.

**Comment by MichalPrincNXP** [comment]
west.yml aligned with mcux-sdk
https://github.com/nxp-mcuxpresso/mcux-sdk-middleware-multicore/commit/08b186255df5ff6c5c84d485456179efa5026854
